apiVersion: v1
kind: Service
metadata:
  labels:
    app: http
  name: node-hello
spec:
  ports:
    - port: 80
      nodePort: 30002
      name: http80
    - port: 8080
      nodePort: 30003
      name: http8080
  type: NodePort
  selector:
    service: node-hello-http-service
