apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: node-hello
  name: node-hello-80
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-hello-80
        service: node-hello-http-service
    spec:
      containers:
        - name: node-hello-80
          image: trumanz/nodejs-hello
          args: [ bash, -c, 
                  "sed -i -- 's/8080/80/g'    /server.js   &&  /run.sh"]
          resources:
            limits:
              cpu: 0.1
          ports:
            - containerPort: 80
              name: http80
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          emptyDir: {}
