apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: dse-cassandra
  name: dse-cassandra
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dse-cassandra
        service: dse
    spec:
      containers:
        - command:
            - /run-cassandra.sh
          resources:
            limits:
              cpu: 0.1
          image: trumanz/dse4kube
          name: dse
          ports:
            - containerPort: 9042
              name: cql
            - containerPort: 9160
              name: thrift
          env:
            - name: MAX_HEAP_SIZE
              value: 1024M
            - name: HEAP_NEWSIZE
              value: 100M
            #TODO
            - name: SERVICE_NAME
              value: dse-service
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /var/lib/cassandra/
              name: data
            - mountPath: /var/log/cassandra/
              name: log
      volumes:
        - name: data
          emptyDir: {}
        - name: log
          emptyDir: {}
