apiVersion: v1
kind: Service
metadata:
  labels:
    app: dse
  name: dse-service
spec:
  ports:
    - name: cql
      port: 9042
      nodePort: 30010
    - name: solr
      port: 8983
      nodePort: 30011
  type: NodePort
  selector:
    service: dse
